export enum MatchEvents {
  NOT_IDLE = 'not_idle',
  NOT_WAITING = 'not_waiting',
  INTRODUCE_EACH_USER = 'introduce_each_user',
  MATCH_RESULT = 'match_result',
  RESTART_MATCHING_REQUEST = 'restart_matching_request',
  PARTNER_DISCONNECTED = 'partner_disconnected',
  START_MATCHING = 'start_matching',
  CANCEL_MATCHING = 'cancel_matching',
  RESPOND_TO_INTRODUCE = 'respond_to_introduce',
  INVALID_RESPOND_TO_INTRODUCE = 'invalid_respond_to_introduce',
  LEAVE_WEBCHAT = 'leave_webchat',
  WEBCHAT_ENDED = 'webchat_ended',
  REQUEST_FACE_RECOGNITION = 'request_face_recognition',
  RESPOND_FACE_RECOGNITION = 'respond_face_recognition',
  PERFORM_FACE_RECOGNITION = 'perform_face_recognition',
  FACE_RECOGNITION_REQUEST_DENIED = 'face_recognition_request_denied',
}
